### ISSUE TITLE
As an author, I want to comment on posts that I can access

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#13]

**Comment by JakeBrand** [comment]
Seems like this is a good place for me to start (in 45 min when my guest is gone for the weekend).
It looks like I'll be working off the dashboard branch as that's quite recent. Any advice in the next 45 min will be appreciated.

**Comment by zturchan** [comment]
Yup, dashboard branch is what you'll want to work in.  I'm gonan try poking at getting the posted post to be viewable on the stream now, which would probably be needed for comment stuff to be working.

**Comment by grepme** [comment]
Probably not a good idea. I cleaned it up a little but you'll need to merge it in #36.

I ran a ton of use cases by it to make it more stable.

**Comment by grepme** [comment]
Comments are dependent on that posts are displayed.

There is still #17, #18, #9 (You need to map to a images startapp that will return the image data based on the settings of the post and the user logged in),

**Comment by grepme** [comment]
Oh, and there are a ton of tests we need written as well

**Comment by grepme** [comment]
Just give me 30 minutes to include the templates for you guys to use and work with

**Comment by zturchan** [comment]
ok sounds good

Zak Turchansky

**Comment by JakeBrand** [comment]
OK. Then I'll start looking at tests for now. That should be independent of the work you guys are doing.
Should I still be working off a branch from dashboard?

**Comment by grepme** [comment]
Nope. Everything is merged except for my stream branch which is almost setup.

**Comment by grepme** [comment]
Okay, done. I built a basic posts template in templates/posts/all.html

Check out the branch "stream"

The idea is you always want to set posts to something and iterate over it. I put in the image url as well because that can be confusing.

**Comment by zturchan** [comment]
Thanks for the template Kyle.  I can implement that to make the posts show up if you'd like, or had you planned on doing that?

**Comment by grepme** [comment]
Nope. That was for you guys. I'm probably done for tonight.

**Comment by zturchan** [comment]
Alright sounds good ^_^

Zak Turchansky

**Comment by JakeBrand** [comment]
I feel close, but I couldn't do it.
1) Comments are not showing up under posts on the dashboard
2) When they do they will be linked manually to the title of a post, so find the guid of the post and use it instead of the title to create and reference comments
3) The single "Add" button is currently hooked up to the new_comment function, that too is not acceptable. The post-specific "Add Comment" buttons should allow the form to appear in a new div and collect the comment text, then another submit button (on that form) should call the new_comment function

once these three things are working I think it's presentable.
Good night and good luck.

**Comment by grepme** [comment]
I cleaned up the comments branch, working on getting it to work now.
![Image of work](https://dl.dropbox.com/u/9108358/ShareX/2015-03/2015-03-10_09-40-39.png)

**Comment by grepme** [comment]
Works now. The comment model, since it was a foreign key means that it exists on the post model with a "comment_set" attribute, which you can then call get, all, etc.
![Works!](https://dl.dropbox.com/u/9108358/ShareX/2015-03/2015-03-10_10-21-53.png)

**Comment by JakeBrand** [comment]
As was the branch was merged and still seems to be working I'm closing this issue.
