### ISSUE TITLE
Setup and use Sphinx

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#18]
See here:
http://sphinx-doc.org

**Comment by varsis** [comment]
Has this been done?

**Comment by grepme** [comment]
Nope.

**Comment by morganpatz** [comment]
So I've tried setting this up multiple times and for some reason cannot get it working. So I need some help. Maybe someone else could give it a try, or we could manually doc. I have time tonight to manually doc if that's our best course of action. Let me know what you guys think we should do? I'm really sorry, I've tried really hard to get this up and running

**Comment by grepme** [comment]
I'd suggest just pulling the gh-pages branch and pushing some HTML on what we have and/or anticipate for the API. That way we get most marks, even if it is half done HTML.

**Comment by JakeBrand** [comment]
Ok. I'll help churn out as much documentation as I can before I leave in a couple hours.
If anyone helping can give me a sample (so we have the same format) and some topics I will do my best. Commenting here and spamming everyone doesn't feel like the best communication method though, so text/email/skype (assassin_jake) is preferred. No mic though, so don't get your hopes up.

**Comment by JakeBrand** [comment]
Have we given up on this?
Should it be closed and removed from the list?

**Comment by zturchan** [comment]
Closing this, we have bigger priorities.  If someone reallllly wants it and it won't take much time I guess you can reopen it.
