### ISSUE TITLE
Add post model

### ISSUE THREAD

**Issue by JakeBrand** [grepme/cmput410-project#25]
I can't seem to get anything working from home, so I wrote up a Post model proposal. I'm sharing it with you all here. My pyCharm crashed twice then wouldn't allow me to save to my Desktop, so I wrote this in notepad. Don't hate me, I probably made mistakes...

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Comment

class Post(models.Model):
    private = 1
    friend = 2
    FOAF = 3
    server = 4
    public = 5
    visibilityChoices = (
        (private, 'Private'),
        (friend, 'Friend'),
        (FOAF, 'Friend of A Friend'),
        (server, 'Server'),
        (public, 'Public'),
    )

```
#55 characters is (usually) enough to show up in a Google search
title = models.CharField(max_length=55)
date = models.DateTimeField(editable=False)
# Not sure how to make a "content" field either text or image
text = models.CharField(max_length=63206, blank=True)
image = models.ImageField(blank=True)
origin = models.GenericIPAddressField(editable=False)
source = models.GenericIPAddressField(editable=False)
author = models.ForeignKey("User", editable=False)
# Can't store arrays of strings, so have to do this a custom way
# http://cramer.io/2008/08/08/custom-fields-in-django/
# categories = SeperatedValuesField(blank=True)
visibility = models.IntegerField(choices=visibilityChoices)
comments = models.ForeignKey("Comment", blank=True)

def __unicode__(self):
    return self.title
```

**Comment by grepme** [comment]
Nicely done with the enum-like syntax for SQLite support.

I made a few changes. We don't need the many-to-one relationship to the comments, so I removed that since it is already in the comment model. I also added in support for the upload_to argument to the /uploads/images/ directory. See the posts branch for more information.

``` python
class Post(models.Model):
    private = 1
    friend = 2
    FOAF = 3
    server = 4
    public = 5
    visibilityChoices = (
        (private, 'Private'),
        (friend, 'Friend'),
        (FOAF, 'Friend of A Friend'),
        (server, 'Server'),
        (public, 'Public'),
    )

    # 55 characters is (usually) enough to show up in a Google search
    title = models.CharField(max_length=55)
    date = models.DateTimeField()
    # Not sure how to make a "content" field either text or image
    text = models.CharField(max_length=63206, blank=True)
    image = models.ImageField(blank=True, upload_to='/images/')
    origin = models.GenericIPAddressField()
    source = models.GenericIPAddressField()
    author = models.ForeignKey(User)
    # Can't store arrays of strings, so have to do this a custom way
    # http://cramer.io/2008/08/08/custom-fields-in-django/
    # categories = SeperatedValuesField(blank=True)
    visibility = models.IntegerField(choices=visibilityChoices)

    def __unicode__(self):
        return self.title
```

**Comment by JakeBrand** [comment]
Model created and merged.

**Comment by zturchan** [comment]
Ok, so I don't think this is done (but I'm real dumb so maybe it is and i'm not seeing it)
However, I don't know if we need these? Is example-article.json part of the spec or just an example?

Post model does not have:
Description 
Categories 
A Guid
Comments

Should These be added to the model and the UI?

**Comment by zturchan** [comment]
My question about example-article.json has been asked on forums here https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=475606

**Comment by grepme** [comment]
Description is the text field in our model.
Categories are the tags.
the guid is added in the dashboard branch now and migrated.
comments are already attached! Check the comment model, it is a many to one model already.
