### ISSUE TITLE
Add Comment Model

### ISSUE THREAD

**Issue by JakeBrand** [grepme/cmput410-project#26]
I can't seem to get anything working from home, so I wrote up a Comment model proposal. I'm sharing it with you all here. My pyCharm crashed twice then wouldn't allow me to save to my Desktop, so I wrote this in notepad. Don't hate me, I probably made mistakes...

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Post

class Comment(models.Model):

```
date = models.DateTimeField(editable=False)
# Not sure how to make a "content" field either text or image
text = models.CharField(max_length=63206, blank=True)
image = models.ImageField(blank=True)
post = models.ForeignKey("Post", editable=False)
inAuthor = models.ForeignKey("User", editable=False)

def __unicode__(self):
    return self.date
```

**Comment by grepme** [comment]
Edit:
Totally ignore that last comment. I've made an edit and this is the actual change:

Okay, I removed editable again like the other pull requests and changed inAuthor to just author for simplicity.

``` python
class Comment(models.Model):
    date = models.DateTimeField()
    # Not sure how to make a "content" field either text or image
    text = models.CharField(max_length=63206, blank=True)
    image = models.ImageField(blank=True)
    post = models.ForeignKey(Post)
    author = models.ForeignKey(User)

    def __unicode__(self):
        return self.date
```

You can check out pull request #33 for more information.

**Comment by JakeBrand** [comment]
Model created and merged.
