### ISSUE TITLE
Add Follow Model

### ISSUE THREAD

**Issue by JakeBrand** [grepme/cmput410-project#28]
I can't seem to get anything working from home, so I wrote up a Follow model proposal. I'm sharing it with you all here. My pyCharm crashed twice then wouldn't allow me to save to my Desktop, so I wrote this in notepad. Don't hate me, I probably made mistakes...

from django.db import models
from django.contrib.auth.models import User

class Follow(models.Model):

```
# when started following
date = models.DateTimeField(editable=False)
# who started following
follower = models.ForeignKey("User", editable=False)
# who was followed
following = models.ForeignKey("User", editable=False)

def __unicode__(self):
    return u'%s -> %s' % self.follower, self.following)
```

**Comment by grepme** [comment]
I've gone ahead and cleaned up this and the Friend model. Models can not be abstract in a many to one relationship without related_name. Also, I got rid of editable, because we need that. That just disables it in /admin from being touched. Please see the follow branch for more information.

``` python
class Follow(models.Model):
    # when started following
    date = models.DateTimeField()
    # who started following
    follower = models.ForeignKey(User, related_name="follower")
    # who was followed
    following = models.ForeignKey(User, related_name="following")

    def __unicode__(self):
        return u"{} -> {}".format(self.follower, self.following)


class Friend(models.Model):
    # when request was accepted
    date = models.DateTimeField()
    # who followed back
    accepter = models.ForeignKey(User, related_name="accepter")
    # who started following
    requester = models.ForeignKey(User, related_name="requester")

    def __unicode__(self):
        return u"{} -> {}".format(self.requester, self.accepter)
```

**Comment by JakeBrand** [comment]
Model created and merged.
