### ISSUE TITLE
Draw wireframes for Design

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#29]
Draw some wireframes for the design

**Comment by zturchan** [comment]
As an author I want to make posts.
    -Dashboard.png, "New Post" Button
As an author, posts I create can link to images.
    -New Post.png, Camera Button
As an author, posts I create be private to me
    -New Post.png, "Share With" dropdown
As an author, posts I create be private to another author
    -New Post.png, "Share With" dropdown
As an author, posts I create be private to my friends
    -New Post.png, "Share With" dropdown
As an author, posts I create be private to friends of friends
    -New Post.png, "Share With" dropdown
As an author, posts I create be private to only friends on my host
    -New Post.png, "Share With" dropdown
As an author, posts I create can be public
    -New Post.png, "Share With" dropdown
As an author, posts I make can be in simple plain text
    -New Post.png, "Plain Text" Radio Button
As an author, posts I make can be in markdown (commonMark is good)
    -New Post.png, "CommonMark" Radio Button
As an author, I want a consistent identity per server
    -Login.png, Required to see your stream
As an author, I want to pull in my github activity to my “stream”
    -Dashboard.png, 2nd post from top
As an author, I want to post posts to my “stream”
    -Dashboard.png, "New Post" Button
As an author, I want to delete my own posts.
    -Dashboard.png, "X" button on post by Zak
As an author, I want to befriend local authors
    -Local Authors.png, "Toggle Friendship" button.
As an author, I want to befriend remote authors
    -Remote Authors.png, "Toggle Friendship" button.
As an author, I want to feel safe about sharing images and posts with my friends – images should not publicly accessible without authentication.
    -Just won't show up if you aren't authed
As an author, I want un-befriend local and remote authors
    -Self Profile.png, "Un-Friend button"" in friend table
    -Local Authors.png, "Toggle Friendship" button.
As an author, I want to be able to use my web-browser to manage my profile
    -Self Profile.png
As an author, I want to be able to use my web-browser to manage/author my posts
    -My Posts.png
As an author, other authors cannot modify my data
    -Self Profile.png, only accessible if you're logged in
As an author, I want to comment on posts that I can access
    -Dashboard.png, Speach bubble buttons on posts
As an author, my server will know about my friends
    -Self Profile.png, Friends list
As an author, When I befriend someone it follows them, only when the other authors befriends me do I count as a real friend.
    -Self Profile.png, Friends list shows unaccepted friend requests
As an author, I want to know if I have friend requests.
    -Self Profile.png, Friends list shows unaccepted friend requests
As an author I should be able to browse the public posts of everyone
    -All Posts.png
As an author I should be able to browse the posts of others depending on my status
    -Dashboard.png (Only followed/friends posts appear)

![local authors](https://cloud.githubusercontent.com/assets/2422050/6520385/227bfa22-c382-11e4-907c-27f1ecbfca5a.png)
![login](https://cloud.githubusercontent.com/assets/2422050/6520386/227db34e-c382-11e4-85ce-294b60347d1b.png)
![my posts](https://cloud.githubusercontent.com/assets/2422050/6520387/228117b4-c382-11e4-9e4a-bde6ce61a8e3.png)
![new post](https://cloud.githubusercontent.com/assets/2422050/6520390/22877168-c382-11e4-8ae0-537b32a2e432.png)
![remote authors](https://cloud.githubusercontent.com/assets/2422050/6520389/22868c08-c382-11e4-975d-449fb9415848.png)
![self profile](https://cloud.githubusercontent.com/assets/2422050/6520388/228458fc-c382-11e4-8ce6-46001f89a48f.png)
![all posts](https://cloud.githubusercontent.com/assets/2422050/6520391/22894bc8-c382-11e4-877b-7bd282d04966.png)
![dashboard](https://cloud.githubusercontent.com/assets/2422050/6520392/228c8018-c382-11e4-9ce2-2ecae16f8286.png)

**Comment by varsis** [comment]
We should throw all this info into a pdf and a folder on the repo so it is easy to find once we close this. I can do it later today.

**Comment by grepme** [comment]
Yep, that would be great, thanks!
