### ISSUE TITLE
Add Wireframes to Wiki

### ISSUE THREAD

**Issue by grepme** [grepme/cmput410-project#46]

**Comment by JakeBrand** [comment]
Which seems preferable?
a) Add the pdf to a wiki page called Planning - Wireframes
b) Add the images to a wiki age called Planning - Wireframes
c) Add the pdf to a wiki page called "what ever you respond with"
d) Add the images to a wiki page called "whatever you respond with"

**Comment by grepme** [comment]
Probably b) in my personal opinion

**Comment by JakeBrand** [comment]
Compact version at [Planning - Wireframes](https://github.com/grepme/cmput410-project/wiki/Planning---Wireframes)
Could do a prettier looking one that would take up more space if desired
