### ISSUE TITLE
Difference between all posts and stream

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#47]
What is the difference between all posts and stream they seem to be exactly the same as far as I can tell.

**Comment by zturchan** [comment]
All posts = every publicly viewable post and post viewable to user
stream = all posts from people i follow/am friends with

Zak Turchansky

**Comment by grepme** [comment]
I don't think I knew the difference either and thus made the wrong query/same query if that is the case.

**Comment by zturchan** [comment]
Yeah, like thing of stream as your facebook news feed (only really see
stuff from your friends).
All posts = anything in your stream, as well as anything thta people mark
as public or visible to FOAF (if you are one), etc

Zak Turchansky

**Comment by varsis** [comment]
I feel like this name is bad .. Didn't click for me
