### ISSUE TITLE
Implement ABC for Models

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#51]
Implement a Abstract Base Class for models. 
Force model to implement as_dict() so when we need a JSON version so it is simple and works. See Posts model for example.

**Comment by morganpatz** [comment]
So this just means adding an appropriate as_dict() method to each model (comments, framework(?), friends, posts (done), tags, and user_profile)?

**Comment by morganpatz** [comment]
I gave this a shot, check out the [pull request #54](https://github.com/grepme/cmput410-project/pull/54) to see if this helps!

**Comment by grepme** [comment]
This seems to be working and we have been using it thus far. Closed until another issue is raised.
