### ISSUE TITLE
As an author, I want to pull in my github activity to my “stream”

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#57]

**Comment by morganpatz** [comment]
Current Progress:
- can mine the data from github and make a new post from /post/new/github (Woooo)
- cannot change the users github username (right now it's hardcoded to mine)
  - need to add github_name field to db (anyone know how I would go about doing this?)
- cannot stream (does not automatically check to see if anything has changed, and generate a post if so)

**Comment by grepme** [comment]
I'll pull this branch down and see what I can get working.

**Comment by grepme** [comment]
Needs some tweaks, but works now.
