### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#66]
Excellent 1: Adheres to standards, well designed
Good 1: Adheres to standards somewhat, some awkward parts
Satisfactory 0: Some good parts, some nasty parts
Unsatisfactory 0: Little effort went into documenting and designing the project

**Comment by zturchan** [comment]
Making a design branch for a bunch of UI updates.

**Comment by grepme** [comment]
What kind of design updates are you doing that are needed?

**Comment by zturchan** [comment]
Shortlist of
-Fix text alignment in posts to be on the left
-Allow you to go to other people's profiles via their posts 
-Allow for listing of all users on server by default for our search (as per Ali's request)
-Display the currently logged in user

More if I think of them/they come up

**Comment by zturchan** [comment]
Design could be reworded to just be UI, maybe poor choice of words on my part
