### ISSUE TITLE
Allow a user to sign up.

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#67]

**Comment by JakeBrand** [comment]
See branch [signup](https://github.com/grepme/cmput410-project/tree/signup):
This looked like it didn't need its own app, so I updated framework to include a signup option.
You can create User objects, but I can't seem to create a Profile (user_profile) object with the User you just created. I'm kind of stuck here but this should be pretty much done.
Any help would be appreciated.

**Comment by JakeBrand** [comment]
Chris helped find it.
Was using id=newUser, not author=newUser

**Comment by varsis** [comment]
Mostly done, but requires some checking. Should duplicate password fields.

**Comment by varsis** [comment]
Is this done jake?

**Comment by JakeBrand** [comment]
Done enough to be use-able yes.
It doesn't take check duplicate passwords and doesn't validate any information, but it allows a user to sign up.

**Comment by JakeBrand** [comment]
Well it used to. Doesn't seem to be letting me create a new user any more.
I'm on the master branch and I can't sign up.
Getting a "Profile matching query does not exist." that I am looking into fixing now.

**Comment by zturchan** [comment]
Jake fixed the above issue and added password double check.  Closing as I don't think this needs anything else.
