### ISSUE TITLE
As an author, I want to post posts to my “stream”

### ISSUE THREAD

**Issue by varsis** [grepme/cmput410-project#7]

**Comment by zturchan** [comment]
I'm gonna work on this and the variants thereof using Kyle template.  Will be done in the stream branch

**Comment by varsis** [comment]
Awesome. I will be needing some sample posts, etc to test the api. I finally figured out how to do some of stuff I needed.

**Comment by zturchan** [comment]
Cool, I"m just pushing some stuff to the dashboard branch now

Zak Turchansky

**Comment by zturchan** [comment]
Ok, the latest dashboard branch lets you make posts and they will show up
in your stream.  Pretty basic, but it works.

Zak Turchansky

**Comment by zturchan** [comment]
OK , who put an invisible hamburger in the code?

![image](https://cloud.githubusercontent.com/assets/2422050/6549246/67e96860-c5d5-11e4-973e-c5be65d5f0c4.png)

**Comment by varsis** [comment]
Lol

**Comment by zturchan** [comment]
OK, so dashboard branch now works for all 3 streams and ux responds appropriately.  They only thing is actually filtering the django query sets, which I wouldn't mid getting some input on.

So they are:
all posts - everything viewable to the currently authenticated user
my posts - this one is already in there and working
stream - my posts + all posts from friends/people I follow.

**Comment by varsis** [comment]
Take a look at my branch. There is some stuff on filtering that might work for you. Also looking into the pagination from django.

**Comment by zturchan** [comment]
Thanks Chris, I think i'm done for the day but i'll take a look at it tomorrow

**Comment by grepme** [comment]
I can probably filter it this morning. I merged your code.

**Comment by grepme** [comment]
This is mostly fixed now in pull request #42
