### ISSUE TITLE
Django Tests Don't Run on Tavis-CI

### ISSUE THREAD

**Issue by grepme** [grepme/cmput410-project#98]
Trying to figure out why this occurs on 'python manage.py test' when it works just fine on my home computer. Any input would be appreciated.

```
Django.db.utils.OperationalError: no such table: api_server
```

Edit: you can see the build information here:
https://travis-ci.org/grepme/cmput410-project/builds/56435142

**Comment by varsis** [comment]
Maybe run migrate, makemigrations before testing?

**Comment by grepme** [comment]
Yeah, I just saw this in the Travis-CI output:

```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

Because it works fine on Vagrant too, just tested it.

**Comment by grepme** [comment]
Commit 0bef6cf with build #291 will tell us more if it worked.

**Comment by grepme** [comment]
Yeah, that fixed that. Closing this.
